### ISSUE TITLE
Use of Visual Studio 2019

### ISSUE THREAD

**Issue by antoniospadea** [ShiftMediaProject/VSNASM#10]
The use of the 'install_script.bat' script does not work and after the manual installation VS2019 returns the error

Severity Code Description Project File Line Suppression State
Error MSB3721 The command "" C: \ Program Files (x86) \ Microsoft Visual Studio \ NASM "nasm.exe -Xvc -f win64 -o" x64 \ Debug \ parteinassembler.obj "" C: \ Users \ cogaa \ source \ repos \ VSeNasm project \ VSeNasm project \ parteinassembler.asm "" exited with code 1.VSeNasm project C: \ Program Files (x86) \ Microsoft Visual Studio \ nasm utility \ nasm.targets 50

I'm not an expert programmer, thanks for the support
I used this test code

section .text 
bits 64 
global foo
foo:
	mov rax,7 
	ret

**Comment by Sibras** [comment]
To start off with how does the 'install_script.bat' not work? what are the error messages it returns?
