### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by AnalogFeelings** [ShiftMediaProject/VSNASM#17]
The install script needs to be adapted for version 17.0 of Visual Studio, and probably for 64 bit as well.

**Comment by Sibras** [comment]
I plan to move to VS2022 once it is released as stable, until I then I dont have a dev machine with it installed in order to check.

If you want to help I need to know the locations that VS2022 installs "vsvasr32.bat" and "vcvars64.bat" and the location of the "BuildCustomizations" folder. If you have 2022 installed and can provide those locations then I can update the install script for you to test.

**Comment by AnalogFeelings** [comment]
I have found those files under my VS2022 install (installed under D:\VS2022):
BuildCustomizations: D:\VS2022\Msbuild\Microsoft\VC\v170
vcvars64.bat and vcvars32.bat seem to be in D:\VS2022\VC\Auxiliary\Build

**Comment by Sibras** [comment]
OK I have pushed an update to the install script in the repo. If you could test it and let me know how it goes that would be appreciated.

**Comment by AnalogFeelings** [comment]
![image](https://user-images.githubusercontent.com/51166756/134550301-9d7b6a1d-bdc0-4758-9334-c4cfc1bc54a9.png)
It seems to spew out a path not found error with VS2022, can I ignore this?

**Comment by Sibras** [comment]
> 
> It seems to spew out a path not found error with VS2022, can I ignore this?

Probably not, unfortunately I dont know where it is generating that message. If you could do a little debugging for me it will help locate the issue.

In the install_script.bat if you could do the following:
Add a new line before line 251 with:
`echo %VCVARS%`

Then add a newline on line 283 with:
```
echo %MSBUILDDIR%
echo %VCTargetsPath%
```
and then post the output when the script is run

**Comment by AnalogFeelings** [comment]
![image](https://user-images.githubusercontent.com/51166756/134701408-b240e763-4bae-4e9e-bbc6-1545d71b6852.png)
It seems to not go back enough to find the "Microsoft" folder.
If I add another ..\ to the path, it apparently works fine.
![image](https://user-images.githubusercontent.com/51166756/134701614-6e105a8d-268f-499f-b3b7-5ed8f7847ca2.png)
![image](https://user-images.githubusercontent.com/51166756/134701628-a02db703-146b-4f79-b4ff-8d0ecc82cefb.png)
Looking at D:\VS2022\Msbuild\Microsoft\VC\v170\BuildCustomizations, it has copied the NASM files succesfully.
![image](https://user-images.githubusercontent.com/51166756/134701785-c43988ae-6ee5-4eef-a50b-0ea520cdc689.png)

**Comment by Sibras** [comment]
Thanks, Ive updated the install script and it should be all good now.
