### ISSUE TITLE
Broken link VS cannot download

### ISSUE THREAD

**Issue by DibyaTheXPFan** [ShiftMediaProject/VSNASM#18]
Detected 64 bit system...
Existing Visual Studio 2019 environment detected...
Installing build customisations...
Downloading required NASM release binary...
Error: Failed to download required NASM binary!
   The following link could not be resolved "http://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip"

**Comment by Sibras** [comment]
The link must have been temporarily down or you need to check your internet/firewall as it is working fine at the moment.
