### ISSUE TITLE
Error: Could not find valid Visual Studio installation!

### ISSUE THREAD

**Issue by ghost** [ShiftMediaProject/VSNASM#22]

**Comment by Jurorno9** [comment]
make sure you are running the installer as administrator

**Comment by liriyao** [comment]
i got the same problem ,i make sure running installer as administrator.did you guys slove this problem?

**Comment by Sibras** [comment]
Run vswhere by itself from the terminal to check what it finds
```
./vswhere.exe -find MSBuild
```

then run the following command

```
./vswhere.exe -prerelease -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
```

If nothing is reported then your visual studio installation is probably incorrect. The most likely issue is that the C++ package has not been properly installed

**Comment by Sibras** [comment]
Closing this as no response from initial user
