### ISSUE TITLE
VS2022 Tool Options

### ISSUE THREAD

**Issue by n0xy1** [ShiftMediaProject/VSNASM#23]
After successfully installing using the `install_script.bat` I am unable to change the `.asm` source file Item Type to be Netwide Assembler

![image](https://github.com/ShiftMediaProject/VSNASM/assets/27118136/b2c99b20-0a1f-45c9-990c-2af9062c3c94)

![image](https://github.com/ShiftMediaProject/VSNASM/assets/27118136/3d568398-02cd-4b9d-9998-b8618b770f94)

![image](https://github.com/ShiftMediaProject/VSNASM/assets/27118136/b438b0d2-da04-46d3-930a-ab594dcf7e9c)

Are you able to provide any info on how to troubleshoot?

**Comment by Sibras** [comment]
I did a reinstall on my end and tested and I cant reproduce the issue.
![image](https://github.com/ShiftMediaProject/VSNASM/assets/5628451/c1d1dd1e-7196-422e-b5a4-e9ab62037087)
With nasm selected in the projects build customisations it should work. Make sure the build customisation is enabled for all projects that contain .asm files. Try saving and restarting VS and make sure there is atleast 1 C/C++ file in the affected project.

**Comment by n0xy1** [comment]
I deployed a new windows development virtual machine, and ran the `install_script.bat` 

I created a new project, changed the build customization, added a new .asm source file and it automatically set the item type to netwide assembler. 

I'm unsure whats different between the two VM's, but its working now. Thanks for your help!

**Comment by davey3223** [comment]
Hey, I know this has been closed already but I have no idea how to open the correct build customization options tab and or the Property pages for my .asm file. Any help would be appreciated. Thanks in advance.

**Comment by Sibras** [comment]
> Hey, I know this has been closed already but I have no idea how to open the correct build customization options tab and or the Property pages for my .asm file. Any help would be appreciated. Thanks in advance.

in the solution explorer window right click the asm file and select properties
