### ISSUE TITLE
error MSB4062: The "SetEnv" task could not be loaded from the assembly Microsoft.Build.CppTasks.Common,

### ISSUE THREAD

**Issue by durongze** [ShiftMediaProject/VSNASM#27]
error MSB4062: The "SetEnv" task could not be loaded from the assembly Microsoft.Build.CppTasks.Common,

**Comment by durongze** [comment]
echo %nasmpath%\nasm.exe
F:\program\nasm\bin\nasm.exe

**Comment by Sibras** [comment]
Thats not the default nasm install path for VSNASM install script. Try and use the bundled installer to install nasm directly into VS

**Comment by durongze** [comment]
> Thats not the default nasm install path for VSNASM install script. Try and use the bundled installer to install nasm directly into VS

thanks
