### ISSUE TITLE
debugging is working?

### ISSUE THREAD

**Issue by ko22009** [ShiftMediaProject/VSNASM#4]
Step by step, breakpoints.

**Comment by Sibras** [comment]
I assume your asking a question as to whether this feature works.

VSNASM does provide a configuration feature to generate debug information that can be used by Visual Studio. This is by default enabled when using a Debug project configuration and can also be manually enabled/disabled from the VSNASM project options dialogue.

And of course given were talking about assembly then Visual Studios dissassembly view can also be always used for step-by-step and breakpoints.
