### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by ko22009** [ShiftMediaProject/VSNASM#5]
Unhandled exception at 0x00D63014 in nasm.exe: 0xC0000005: Access violation when reading at address 0xFFFFFFFF.

**Comment by Sibras** [comment]
This is clearly an error with nasm itself. This project only deals with creating an easy Visual Studio integration for nasm. Any error related to the nasm program itself should be sent to the actual nasm maintainers ([https://www.nasm.us/](https://www.nasm.us/))
