### ISSUE TITLE
VS 2017, debugging doesn't work

### ISSUE THREAD

**Issue by ko22009** [ShiftMediaProject/VSNASM#6]
If I run compatible with VS 2010, I cannot debug app.
And for VS 2017 I should use msvcrt.lib;legacy_stdio_definitions.lib (and also debugging doesn't work)

**Comment by Sibras** [comment]
You don't need to manually link to msvcrt.lib;legacy_stdio_definitions.lib to use nasm. That is only required if you link an external library built using an older (i.e. pre 2017) compiler version. Your nasm code shouldn't use any msvc c runtime functions so it doesn't need any of these libs.

As for debugging it appears that current VS doesn't support the cv8 debug format that nasm is generating. I checked and nasm is producing debug info but it appears that VS doesn't recognize it completely. This seems to be an issue with nasm itself and so there is nothing that I can do on my end.

You can however still use the dissassembly window to step through the assembly code for debugging.
